# Generated by Django 5.2.5 on 2025-08-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('dates', models.JSONField(default=dict)),
                ('generalMemory', models.CharField(max_length=1024)),
            ],
        ),
    ]
