# Generated by Django 5.2.5 on 2025-08-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemory',
            name='dates',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='usermemory',
            name='generalMemory',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
